version: '3.8'
services:
    base:
        container_name: ${COMPOSE_NAME}.${BASE_IMAGE}
        image: ${COMPOSE_NAME}/${BASE_IMAGE}
        build:
            context: .
            args:
                - NODE_VERSION=${NODE_VERSION}
                - SCRATCH_VERSION=${SCRATCH_VERSION}
            dockerfile: base.Dockerfile
