version: '3.8'
services:
    website:
        restart: unless-stopped
        container_name: ${COMPOSE_NAME}.${APPLEPTR16_IMAGE}
        image: ${COMPOSE_NAME}/${APPLEPTR16_IMAGE}
        build:
            context: .
            dockerfile: ./apps/website/Dockerfile
            args:
                - NGINX_VERSION=${NGINX_VERSION}
                - NODE_VERSION=${NODE_VERSION}
        environment:
            - NGINX_PORT=${NGINX_PORT}
        ports:
            - '${NGINX_PORT}:${NGINX_PORT}'
        networks:
            - 'appleptr16'
networks:
    appleptr16:
        name: appleptr16
