version: '3.8'
services:
    website:
        restart: unless-stopped
        container_name: ${COMPOSE_NAME}.${APPLEPTR16_IMAGE}
        image: docker.appleptr16.com/${COMPOSE_NAME}/${APPLEPTR16_IMAGE}
        environment:
            - NGINX_PORT=${NGINX_PORT}
        networks:
            - 'appleptr16'
networks:
    appleptr16:
        name: appleptr16
